-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("sh -c '/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh &'")
	hl.exec_cmd("sh -c 'hypridle &'")
	hl.exec_cmd("sh -c 'cliphist wipe &'")
	hl.exec_cmd("sh -c 'wl-paste --watch cliphist store &'")
	hl.exec_cmd("sh -c '" .. bar .. " " .. barOptions .. " &'")
	hl.exec_cmd("sh -c 'swaync &'")
	hl.exec_cmd("sh -c 'hyprpaper &'")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("sh -c 'eww daemon &'")
	hl.exec_cmd("sh -c 'hyprctl setcursor " .. cursor_theme .. "'")
	hl.exec_cmd("sh -c 'spotify-launcher &'")
	hl.exec_cmd("sh -c 'alacritty -t cava -e cava &'")
	hl.exec_cmd("sh -c 'alacritty -t tty-clock -e tty-clock -b -c -C 7 -S -n &'")
end)
